use_frameworks!

target 'LYSegmentController_Example' do
  pod 'LYSegmentController', :path => '../'

  target 'LYSegmentController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
